name: certupdate
on:
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:
  repository_dispatch:
    types: [build]
    
jobs:
  certupdate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Credentials
        env: 
          EMAIL: ${{ secrets.EMAIL }}
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          cat > ~/.netrc <<EOF
            machine api.heroku.com
              login $EMAIL
              password $API_KEY
          EOF
      - name: CD
        env:
          APP: "nixsanctuary"
          EMAIL: ${{ secrets.EMAIL }}
          API_KEY: ${{ secrets.API_KEY }}
          DOCKER_OPTIONS: "--no-cache"
        run: |
          certbot certonly --manual \
          --rsa-key-size 4096 \
          --preferred-challenges=dns \
          --email ${EMAIL} \
          --server https://acme-v02.api.letsencrypt.org/directory \
          --agree-tos \
          -d nixsanctuary.com
          sudo heroku certs:update /etc/letsencrypt/live/nixsanctuary.com/fullchain.pem /etc/letsencrypt/live/nixsanctuary.com/privkey.pem
